server:
  port: 9989


spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        service: ${spring.application.name}
feign:
  hystrix:
    enabled: true