server:
  port: 2202


spring:
  profiles:
    active: after_route
  application:
    name: cloud-gateway

---
spring:
  profiles: after_route
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        service: ${spring.application.name}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: nacos-consumer
          uri: lb://nacos-consumer
          predicates:
            - Path=/nacos/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456


